version: '3'
services:
  webserver:
    container_name: sportddd_webserver
    build: ./config/docker/webserver
    ports:
      - '80:80'
    volumes:
      - './:/var/www/html/'
  mysql:
    container_name: sportddd_mysql
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: sportddd
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
  mail:
    container_name: sportddd_mail
    image: registry.hub.docker.com/mailhog/mailhog
    ports:
      - '8025:8025'